# TCL File Generated by Component Editor 23.1
# Thu Dec 05 15:53:18 MST 2024
# DO NOT MODIFY


# 
# buzzer "buzzer" v1.0
#  2024.12.05.15:53:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module buzzer
# 
set_module_property DESCRIPTION ""
set_module_property NAME buzzer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME buzzer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL buzzer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file buzzer.vhd VHDL PATH ../hdl/buzzer/buzzer.vhd TOP_LEVEL_FILE
add_fileset_file pwm_controller.vhd VHDL PATH ../hdl/pwm/pwm_controller.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point buzzer_control
# 
add_interface buzzer_control avalon end
set_interface_property buzzer_control addressUnits WORDS
set_interface_property buzzer_control associatedClock clk
set_interface_property buzzer_control associatedReset rst
set_interface_property buzzer_control bitsPerSymbol 8
set_interface_property buzzer_control burstOnBurstBoundariesOnly false
set_interface_property buzzer_control burstcountUnits WORDS
set_interface_property buzzer_control explicitAddressSpan 0
set_interface_property buzzer_control holdTime 0
set_interface_property buzzer_control linewrapBursts false
set_interface_property buzzer_control maximumPendingReadTransactions 0
set_interface_property buzzer_control maximumPendingWriteTransactions 0
set_interface_property buzzer_control readLatency 0
set_interface_property buzzer_control readWaitTime 1
set_interface_property buzzer_control setupTime 0
set_interface_property buzzer_control timingUnits Cycles
set_interface_property buzzer_control writeWaitTime 0
set_interface_property buzzer_control ENABLED true
set_interface_property buzzer_control EXPORT_OF ""
set_interface_property buzzer_control PORT_NAME_MAP ""
set_interface_property buzzer_control CMSIS_SVD_VARIABLES ""
set_interface_property buzzer_control SVD_ADDRESS_GROUP ""

add_interface_port buzzer_control avs_address address Input 1
add_interface_port buzzer_control avs_read read Input 1
add_interface_port buzzer_control avs_write write Input 1
add_interface_port buzzer_control avs_readdata readdata Output 32
add_interface_port buzzer_control avs_writedata writedata Input 32
set_interface_assignment buzzer_control embeddedsw.configuration.isFlash 0
set_interface_assignment buzzer_control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment buzzer_control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment buzzer_control embeddedsw.configuration.isPrintableDevice 0


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clk
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export buzzer_out buzzer_out Output 1

