# TCL File Generated by Component Editor 23.1
# Fri Dec 06 12:42:54 MST 2024
# DO NOT MODIFY


# 
# led_array "led_array" v1.0
#  2024.12.06.12:42:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_array
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_array
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME led_array
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_array
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_array.vhd VHDL PATH ../hdl/LED-array/led_array.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point led_array
# 
add_interface led_array avalon end
set_interface_property led_array addressUnits WORDS
set_interface_property led_array associatedClock clk
set_interface_property led_array associatedReset rst
set_interface_property led_array bitsPerSymbol 8
set_interface_property led_array burstOnBurstBoundariesOnly false
set_interface_property led_array burstcountUnits WORDS
set_interface_property led_array explicitAddressSpan 0
set_interface_property led_array holdTime 0
set_interface_property led_array linewrapBursts false
set_interface_property led_array maximumPendingReadTransactions 0
set_interface_property led_array maximumPendingWriteTransactions 0
set_interface_property led_array readLatency 0
set_interface_property led_array readWaitTime 1
set_interface_property led_array setupTime 0
set_interface_property led_array timingUnits Cycles
set_interface_property led_array writeWaitTime 0
set_interface_property led_array ENABLED true
set_interface_property led_array EXPORT_OF ""
set_interface_property led_array PORT_NAME_MAP ""
set_interface_property led_array CMSIS_SVD_VARIABLES ""
set_interface_property led_array SVD_ADDRESS_GROUP ""

add_interface_port led_array avs_address address Input 1
add_interface_port led_array avs_read read Input 1
add_interface_port led_array avs_readdata readdata Output 32
add_interface_port led_array avs_write write Input 1
add_interface_port led_array avs_writedata writedata Input 32
set_interface_assignment led_array embeddedsw.configuration.isFlash 0
set_interface_assignment led_array embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment led_array embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment led_array embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clk
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export led led Output 8

